"""Live MAVLink attack proxy (Stage 2, P2). See docs/ATTACK_PROXY.md."""

from .attacks_live import (
    COMMAND_INJECTION_RANGES,
    RANGES,
    CommandInjectionAttack,
    CommandInjectionParams,
    PositionDriftAttack,
    PositionDriftParams,
    draw_command_injection_params,
    draw_params,
)
from .attacks_live_dos_replay import (
    DELAY_RANGES,
    DROP_RANGES,
    REPLAY_RANGES,
    DelayAttack,
    DelayParams,
    DropAttack,
    DropParams,
    ReplayAttack,
    ReplayParams,
    draw_delay_params,
    draw_drop_params,
    draw_replay_params,
)
from .groundtruth import (
    FrameLogEntry,
    FrameLogWriter,
    Manifest,
    compute_actual_effect,
    compute_command_injection_effect,
    compute_delay_effect,
    compute_drop_effect,
    compute_replay_effect,
    is_holdout,
    read_frame_log,
    read_manifest,
    write_manifest,
)
from .hooks import FrameContext, FrameHook, passthrough

__all__ = [
    "COMMAND_INJECTION_RANGES",
    "DELAY_RANGES",
    "DROP_RANGES",
    "RANGES",
    "REPLAY_RANGES",
    "CommandInjectionAttack",
    "CommandInjectionParams",
    "DelayAttack",
    "DelayParams",
    "DropAttack",
    "DropParams",
    "FrameContext",
    "FrameHook",
    "FrameLogEntry",
    "FrameLogWriter",
    "Manifest",
    "PositionDriftAttack",
    "PositionDriftParams",
    "ReplayAttack",
    "ReplayParams",
    "compute_actual_effect",
    "compute_command_injection_effect",
    "compute_delay_effect",
    "compute_drop_effect",
    "compute_replay_effect",
    "draw_command_injection_params",
    "draw_delay_params",
    "draw_drop_params",
    "draw_params",
    "draw_replay_params",
    "is_holdout",
    "passthrough",
    "read_frame_log",
    "read_manifest",
    "write_manifest",
]
